config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
                  path("__debug__/", include("debug_toolbar.urls")),
    path('', include('petowner.urls', namespace='petowner')),
    path('', include('pet.urls', namespace='pet')),
    path('', include('core.urls')),
    path('accounts/', include('core.urls')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('accounts/', include('allauth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet/urls.py
from django.urls import path

from . import views

app_name = 'pet'

urlpatterns = [
    path('api/pets/<int:pk>/delete', views.PetDeleteAPIView.as_view(), name='api_delete'),
    path('api/pets/temperature', views.PetTemperatureCreateAPIView.as_view(), name='api_temperature'),
    path('api/pets/coordinate', views.PetCoordinateCreateAPIView.as_view(), name='api_coordinate'),
    path('pets/<int:pk>/update', views.PetUpdateView.as_view(), name='update'),
    path('pets/list', views.PetListView.as_view(), name='list'),
]

petowner/urls.py
from django.urls import path

from . import views

app_name = 'petowner'

urlpatterns = [
    path('petowner/<int:pk>/edit/', views.PetOwnerUpdateView.as_view(), name='edit'),
    path('api/petowner/new/', views.PetOwnerCreateAPIView.as_view(), name='new_api'),
    path('api/petowner/<int:pk>/delete', views.PetOwnerDeleteAPIView.as_view(), name='api_delete'),
    path('petowner/<int:pk>/pets', views.PetOwnerPetListView.as_view(), name='pet_list'),
    path('petowner/api/pets/create', views.PetOwnerCreatePetView.as_view(), name='pet_create'),
]

templates/Pages/pet_delete.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Delete Pet</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">
            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">
                    <div class="portlet-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <img id="imgProfile1"
                                         src="{% static '' %}{{ object.image }}"
                                         alt="profile image"
                                         class="img-circle img-responsive img_profile_Right VDimgUser">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Name: {{ object.name }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Breed: {{ object.breed }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Age: {{ object.age }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Birthdate: {{ object.birthdate }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    ID Number: {{ object.serial_number }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <input class="btn btn-danger btn-round" type="submit" value="Delete">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <a class="btn btn-cyan btn-round" href="{% url 'index' %}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /#page-content -->

        <style>
            .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
                color: #f55145;

            }
        </style>

        <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

{% endblock PageContent %}

templates/Pages/pet_list.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Pets</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">


            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">

                    <div class="portlet-body">

                        <div i class="table-responsive">
                            <table id="petListTable" class="table table-striped table-bordered dt-responsive nowrap"
                                   width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Breed</th>
                                    <th>Birthdate</th>
                                    <th>Image</th>
                                    <th>ID</th>
                                    <th>Owner</th>
                                    <th>Actions</th>
                                </tr>
                                {% for pet in pets %}
                                    <tr>
                                        <td>{{ pet.name }}</td>
                                        <td>{{ pet.type }}</td>
                                        <td>{{ pet.breed }}</td>
                                        <td>{{ pet.birthdate }}</td>
                                        <td><img src="{{ pet.image.url }}" alt="pet image" width="100px"></td>
                                        <td>{{ pet.serial_number }}</td>
                                        <td>{{ pet.petowner.user.username }}</td>
                                        <td>
                                            <button class="btn btn-sm  DeletT" title="Delete"
                                                    onclick="delete_pet_btn({{ pet.id }}, '{{ pet.name }}')">
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            </button>
                                            <a href="{% url 'pet:update' pet.id %}"
                                               class="btn btn-sm  EditT" title="Edit">
                                                <i class="fa fa-edit fa-2x"></i>
                                            </a>
                                            <a href="{% url 'petowner:edit' pet.petowner.user.id %}"
                                               class="btn btn-sm" title="Owner">
                                                <img src="{{ pet.petowner.user.image.url }}" alt="pet owner image"
                                                     class="rounded-circle" width="30" height="30">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </thead>
                            </table>
                        </div>


                    </div>

                </div>
            </div>


        </div>

    </div><!-- /#page-content -->

    <style>
        .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
            color: #f55145;

        }
    </style>

    <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

    <script src="{% static '/js/delete.js' %}"></script>


{% endblock PageContent %}

templates/Pages/pet_update.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    {% load crispy_forms_tags %}

    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Edit Pet</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>


        <div id="recordDetail" class="row justify-content-center">


            <div class="col-lg-7 col-12">
                <div class="portlet box border shadow">

                    <div class="portlet-body">


                        <div class="row">

                            <div class="col-12">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab23">
                                        <fieldset>
                                            <input type="hidden" id="hfId"/>
                                            <form method="POST" role="form" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                {{ form.non_field_errors }}
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-group ">
                                                            {{ form.name.errors }}
                                                            <label for="{{ form.name.id_for_label }}"> {{ form.name.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                        <span class="input-group-addon">
                                                            <i class="icon-user"></i>
                                                        </span>
                                                                <input type="text"
                                                                       name="{{ form.name.html_name }}"
                                                                       placeholder="{{ form.name.label }}"
                                                                       id="{{ form.name.auto_id }}"
                                                                       value="{{ form.name.value|default_if_none:'' }}">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group ">
                                                            {{ form.type.errors }}
                                                            <label for="{{ form.type.id_for_label }}"> {{ form.type.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                        <span class="input-group-addon">
                                                            <i class="icon-user"></i>
                                                        </span>
                                                                <input type="text" name="{{ form.type.html_name }}"
                                                                       placeholder="{{ form.type.label }}"
                                                                       id="{{ form.type.auto_id }}"
                                                                       value="{{ form.type.value|default_if_none:'' }}">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-group ">
                                                            {{ form.breed.errors }}
                                                            <label for="{{ form.breed.id_for_label }}"> {{ form.breed.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                        <span class="input-group-addon">
                                                            <i class="icon-user"></i>
                                                        </span>
                                                                <input type="text" name="{{ form.breed.html_name }}"
                                                                       placeholder="{{ form.breed.label }}"
                                                                       id="{{ form.breed.auto_id }}"
                                                                       value="{{ form.breed.value|default_if_none:'' }}">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group ">
                                                            {{ form.birthdate.errors }}
                                                            <label for="{{ form.birthdate.id_for_label }}"> {{ form.birthdate.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                        <span class="input-group-addon">
                                                            <i class="icon-user"></i>
                                                        </span>
                                                                <input type="date" onfocus='this.showPicker()'
                                                                       name="{{ form.birthdate.html_name }}"
                                                                       placeholder="{{ form.birthdate.label }}"
                                                                       id="{{ form.birthdate.auto_id }}"
                                                                       value="{{ form.birthdate.value|date:"Y-m-d" }}">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col">
                                                        <div>
                                                            {{ form.image.errors }}
                                                            <label for="{{ form.image.id_for_label }}"> {{ form.image.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                                <span class="input-group-addon">
                                                                    <i class="icon-user"></i>
                                                                </span>
                                                                <input type="file"
                                                                       accept="image/*"
                                                                       name="{{ form.image.html_name }}"
                                                                       placeholder="{{ form.image.label }}"
                                                                       id="{{ form.image.auto_id }}"
                                                                       value="{{ form.image.value|default_if_none:'' }}">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                    <div class="col">
                                                        <div class="form-group ">
                                                            {{ form.serial_number.errors }}
                                                            <label for="{{ form.serial_number.id_for_label }}"> {{ form.serial_number.label }}:
                                                            </label>
                                                            <div class="input-group round">
                                                        <span class="input-group-addon">
                                                            <i class="icon-user"></i>
                                                        </span>
                                                                <input type="text"
                                                                       name="{{ form.serial_number.html_name }}"
                                                                       placeholder="{{ form.serial_number.label }}"
                                                                       id="{{ form.serial_number.auto_id }}"
                                                                       value="{{ form.serial_number.value|default_if_none:'' }}"
                                                                       readonly="readonly">
                                                            </div><!-- /.input-group -->
                                                        </div><!-- /.form-group -->
                                                    </div>
                                                </div>
                                                <div class="form-actions text-center mt-3">
                                                    <button type="submit" class="btn btn-success btn-curve">
                                                        <i class="icon-check"></i>
                                                        Confirm
                                                    </button>
                                                </div>
                                            </form>
                                        </fieldset>
                                    </div><!-- /.tab-pane -->


                                </div><!-- /.tab-content -->
                            </div><!-- /.col-9 -->
                        </div><!-- /.row -->


                    </div><!-- /.portlet-body -->
                </div><!-- /.portlet -->
            </div><!-- /.col-lg-8 -->

        </div>


    </div><!-- /#page-content -->

    <style>
        .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
            color: #f55145;

        }
    </style>

    <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

{% endblock PageContent %}

templates/Pages/petowner_delete.html
{% extends 'Pages/Shared/_Layout.html' %}
{% block PageContent %}
    {% load static %}
    <div id="page-content">
        <div class="row">
            <!-- BEGIN BREADCRUMB -->
            <div class="col-md-12">
                <div class="breadcrumb-box border shadow">
                    <ul class="breadcrumb">
                        <li><a id="ttlPage" href="#">Delete Pet owner</a></li>
                    </ul>
                    <div class="breadcrumb-right">

                    <span class="dateToday">
                        Fri, 26 Aug 2022
                    </span>
                        <i class="icon-calendar"></i>
                    </div><!-- /.breadcrumb-right -->
                </div><!-- /.breadcrumb-box -->
            </div><!-- /.col-md-12 -->
            <!-- END BREADCRUMB -->
        </div>

        <div id="gridUser" class="row justify-content-center">
            <div class=" col-lg-10  col-12">
                <div class="portlet box border shadow">
                    <div class="portlet-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <img id="imgProfile1"
                                         src="{% static '' %}{{ object.image }}"
                                         alt="profile image"
                                         class="img-circle img-responsive img_profile_Right VDimgUser">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    Full name: {{ object.first_name }} {{ object.last_name }}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <input class="btn btn-danger btn-round" type="submit" value="Delete">
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col">
                                    <a class="btn btn-cyan btn-round" href="{% url 'index' %}">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /#page-content -->

        <style>
            .error, .has-error + .help-block, .has-error .checkbox, .has-error .checkbox-inline, .has-error .control-label, .has-error .help-block, .has-error .radio, .has-error .radio-inline, .has-error.checkbox label, .has-error.checkbox-inline label, .has-error.radio label, .has-error.radio-inline label {
                color: #f55145;

            }
        </style>

        <link href="{% static 'assets/plugins/data-table/css/jquery.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/data-table/css/buttons.dataTables.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'assets/plugins/select2/dist/css/select2.min.css' %}" rel="stylesheet">

{% endblock PageContent %}